openapi: 3.0.0
info:
  title: YouTube Media Downloader API
  description: A lightweight Node.js API for fetching YouTube metadata and downloading video/audio using yt-dlp.
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /info:
    get:
      summary: Fetch Video Metadata
      parameters:
        - name: url
          in: query
          required: true
          description: YouTube video URL
          schema:
            type: string
      responses:
        '200':
          description: Successful response with video metadata
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: dQw4w9WgXcQ
                  title:
                    type: string
                    example: Never Gonna Give You Up
                  thumbnail:
                    type: string
                    example: https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg
                  duration:
                    type: integer
                    example: 213
                  formats:
                    type: array
                    items:
                      type: object
                      properties:
                        format_id:
                          type: string
                          example: "18"
                        ext:
                          type: string
                          example: mp4
                        resolution:
                          type: string
                          example: 360p
                        filesize:
                          type: integer
                          example: 48762132
        '400':
          description: Bad request, invalid URL
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid URL

  /download:
    post:
      summary: Download Video or Audio
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: YouTube video URL
                  example: https://youtube.com/watch?v=dQw4w9WgXcQ
                format_id:
                  type: string
                  description: Format to download (from /info)
                  example: "18"
                type:
                  type: string
                  description: Type of media to download (video or audio)
                  example: audio
      responses:
        '200':
          description: Successful response with downloadable stream
        '400':
          description: Bad request, invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid parameters
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Too many requests, please try again later.